# Select compose version
version: "3"
# Define services
services: 
    # Create template service
    application:
        # Select service image
        build: application
        # Expose ports
        ports: 
            - 8000:80
        # Mount volumes
        volumes:
            # Persistent data volume
            - data:/opt
            # Docker engine volume
            - /var/run/docker.sock:/var/run/docker.sock
        # Environment variables
        environment:
            - PASSWORD=TestPassword1

volumes:
    data: