name: Build and push multi-arch images

on:
    push:
        branches: master

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Code setup
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: QEMU setup
              uses: docker/setup-qemu-action@v2

            - name: Buildx setup
              uses: docker/setup-buildx-action@v2

            - name: DockerHub setup
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.NAME }}
                  password: ${{ secrets.TOKEN }}

            - name: Tags setup
              run: |
                  echo "DATE=$(date +%Y.%m.%d)" >> $GITHUB_ENV
                  echo "LATEST=latest" >> $GITHUB_ENV

            - name: Build and push
              uses: docker/build-push-action@v2

              with:
                  # Build properties
                  file: application/Dockerfile
                  context: application
                  platforms: linux/amd64,linux/arm/v7,linux/arm64/v8

                  # Docker properties
                  push: true
                  tags: |
                      dockervisor/composervisor:${{ env.DATE }}
                      dockervisor/composervisor:${{ env.LATEST }}
